// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationDotNetCoreGLSIA.Models;

#nullable disable

namespace WebApplicationDotNetCoreGLSIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230404120905_AddImageFileToProduct")]
    partial class AddImageFileToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProduitssCategorie", b =>
                {
                    b.Property<Guid>("produitsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("sscategsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("produitsId", "sscategsId");

                    b.HasIndex("sscategsId");

                    b.ToTable("ProduitssCategorie");
                });

            modelBuilder.Entity("WebApplicationDotNetCoreGLSIA.Models.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("A");

                    b.HasKey("Id");

                    b.ToTable("Categs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca72b856-c29b-4df4-89e3-14b6586d512a"),
                            Name = "test"
                        },
                        new
                        {
                            Id = new Guid("d3d3a0db-f8c0-4cf9-a643-ed85feea7f3a"),
                            Name = "TestFromJsonFile"
                        });
                });

            modelBuilder.Entity("WebApplicationDotNetCoreGLSIA.Models.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAjoutProduit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("produits");
                });

            modelBuilder.Entity("WebApplicationDotNetCoreGLSIA.Models.ssCategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SubCatName");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("SousCategories");
                });

            modelBuilder.Entity("ProduitssCategorie", b =>
                {
                    b.HasOne("WebApplicationDotNetCoreGLSIA.Models.Produit", null)
                        .WithMany()
                        .HasForeignKey("produitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationDotNetCoreGLSIA.Models.ssCategorie", null)
                        .WithMany()
                        .HasForeignKey("sscategsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplicationDotNetCoreGLSIA.Models.ssCategorie", b =>
                {
                    b.HasOne("WebApplicationDotNetCoreGLSIA.Models.Categorie", "categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
